{% set name = "ersilia" %}
{% set version = "0.1.40" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ersilia-os/ersilia/archive/v{{ version }}.tar.gz
  sha256: 5c61cc3d161736aeca7495c15c77619d7830346b84514dbe36060cfbdc78065a

build:
  entry_points:
    - ersilia = ersilia.cli:cli
    - bentoml = ersilia.setup.requirements:check_bentoml
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - inputimeout >=1.0.4,<2.0.0
    - emoji >=2.8.0,<3.0.0
    - validators >=0.21.0,<0.22.0
    - psutil >=5.9.0
    - h5py >=3.7.0,<4.0.0
    - loguru >=0.6.0,<0.7.0
    - pyyaml >=6.0.1,<7.0.0
    - dockerfile-parse >=2.0.1,<3.0.0
    - tqdm >=4.66.1,<5.0.0
    - click >=8.1.7,<9.0.0
    - docker-py >=7.1.0,<8.0.0
    - boto3 >=1.28.40,<2.0.0
    - requests >=2.31.0,<3.0.0
    - numpy <=1.26.4
    - aiofiles <=24.1.0
    - aiohttp >=3.10.11
    - nest-asyncio <=1.6.0
    - setuptools >=70.0.0,<71.0.0
  run_constrained:
    - isaura 0.1
    - pytest >=7.4.0,<8.0.0
    - fuzzywuzzy >=0.18.0,<0.19.0
    - sphinx >=5.3.0
    - jinja2 >=3.1.2,<4.0.0

test:
  imports:
    - ersilia
  commands:
    - pip check
    - ersilia --help
    - bentoml --help
  requires:
    - pip

about:
  home: https://ersilia.io
  license: GPL-3.0-only
  license_file:
    - LICENSE
  summary: 'A hub of AI/ML models for open source drug discovery and global health'
  dev_url: https://github.com/ersilia-os/ersilia

extra:
  recipe-maintainers:
    - DhanshreeA
